name: fluttermvvmtemplate
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.16.2 <3.0.0"
dependencies:
  build_runner: ^2.1.11
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_mobx: ^2.0.6+1
  json_annotation: ^4.5.0
  json_serializable: ^6.2.0
  mobx: ^2.0.7+3
  mobx_codegen: ^2.0.7
  provider: ^6.0.3
  shared_preferences: ^2.0.15
dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - asset/lang/
